# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-FreeDB
version:      0.07
version_from: FreeDB.pm
installdirs:  site
requires:
    CDDB::File:                    1.01
    Net::Cmd:                      2.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
